services:
  - type: web
    name: booknest-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    plan: free
    env:
      - key: NODE_VERSION
        value: 20

  - type: web
    name: booknest-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    plan: free
    env:
      - key: NODE_VERSION
        value: 20
      - key: VITE_API_URL
        value: https://booknest-api-hu40.onrender.com
